### ISSUE TITLE
MIDI dont work in Yosemite

### ISSUE THREAD

**Issue by Whyiamdead** [Wouter1/EMU-driver#62]
In Yosemite 10.10.3 after installing the driver, gone a sound problem, everything is perfect.
But now there is no MIDI interface in the device list.

**Comment by Wouter1** [comment]
Thanks for reporting and for your interest in my driver.

This issue is known issue #44. But your report now confirms that this is not working (#44 was only an expectation).

I can not fix #44 because I have nothing to test with.

If you are willing to help a bit on this issue, maybe you can indicate so in ticket #44. I will then try to resurrect some old code that supposedly did midi stuff and see if that works.
